# permissions for end users to view secondkindtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secondkindtest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: guestbook
    app.kubernetes.io/part-of: guestbook
    app.kubernetes.io/managed-by: kustomize
  name: secondkindtest-viewer-role
rules:
- apiGroups:
  - webapp.matysiaq.tech
  resources:
  - secondkindtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.matysiaq.tech
  resources:
  - secondkindtests/status
  verbs:
  - get
